title: <p align="center"> Narendra Sannabhadti </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/narendrasan/">LinkedIn</a> |
  <a href="https://github.com/narendras9">GitHub</a>
  
  <br>   
  I'm entrepreneur working on solving business problems using Data Science.
  
  <br>
  </p>



theme: jekyll-theme-minimal
